version: '4.0'

services:
  batool:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
      tags:
        - batool
    environment:
      UID: 1000
      GID: 1000
    volumes:
      - ./extracted:/home/python/code/extracted
      - ./raw:/home/python/code/raw
      - ./BlueArchive.fbs:/home/python/code/BlueArchive.fbs
      - ./dump.cs:/home/python/code/dump.cs
      - ./version.txt:/home/python/code/version.txt